version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/code"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directories: 
      - "/infrastructure/*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
